### ISSUE TITLE
Could not find a version that satisfies the requirement

### ISSUE THREAD

**Issue by Landei** [kiliankoe/dvbpy#10]
```
pi@RASPBERRYPI2 ~ $ sudo pip install dvbpy
Collecting dvbpy
  Could not find a version that satisfies the requirement dvbpy (from versions: )
No matching distribution found for dvbpy
```
Every time when I try to install dvbpy on my Raspberry Pi2

**Comment by kiliankoe** [comment]
I'm unfortunately not an expert on pip or pypi usage. Maybe @lucaswo or @h4llow3En know a bit more?

It's suggested online that maybe not all requirements are contained in our requirements.txt, but `pip freeze` lists only numpy, pyproj and requests for me. Odd.

Others suggest running `pip install --user dvbpy` in this case. Or maybe you can run `pip install -vvv dvbpy` and drop the output here. Hopefully that contains a bit more info.

**Comment by h4llow3En** [comment]
You have to use Python 3.
Unless you use arch on your Pi you have to use `pip3 install ...`

**Comment by dirkonet** [comment]
You might also want to try `pip3 install dvb` instead of `… dvbpy`.

**Comment by kiliankoe** [comment]
Looks like the readme states otherwise, that's unfortunate :D I'm guessing the installation name corresponds with the name given in the setup.py?
