### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by balzer82** [kiliankoe/dvbpy#12]
```
import dvb
  
 File "/Users/balzer82/anaconda/lib/python2.7/site-packages/dvb/dvb.py", line 7
    def monitor(stop, offset=0, limit=10, city='Dresden', *, raw=False):
                                                           ^
SyntaxError: invalid syntax
```

**Comment by kiliankoe** [comment]
I can't recall why the `*` param is in there... @h4llow3En, do you? 

But it seems that that syntax doesn't work in Python 2, but does in Python 3.

**Comment by h4llow3En** [comment]
This is a feature of Python3 and this pip package is Python 3 only.
`*` Catches all following unnamed commands and forces to call the `raw` param with name.

**Comment by kiliankoe** [comment]
Ah, thanks for the explanation. Python3 ftw I guess.

**Comment by balzer82** [comment]
OK. I `pip install` it with Python 2.7
