### ISSUE TITLE
Figure out a way to work with the MDV coordinates

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/dvbpy#2]
There's got to be a way...

**Comment by ubahnverleih** [comment]
I think MDV is just the name for MentzDV and has nothing to with the coordinates.
But it looks like there are in GK4: http://epsg.io/5678
So GDAL/OGR or Proj4 should solve the problem

**Comment by ubahnverleih** [comment]
using pyproj (proj4 for Python) you can convert the coords this way:

```python
import pyproj

lng = 4622580
lat = 5656350

wgs = Proj(init='epsg:4326')
gk4 = pyproj.Proj(init='epsg:5678')

lngOut, latOut = transform(gk4,wgs,lng,lat)
```

**Comment by kiliankoe** [comment]
No way! :open_mouth:

I think I love you, Consti! :D Unless you want to make a PR, I'll be throwing this in the next few days, thank you!

**Comment by ubahnverleih** [comment]
thanks :)
PR is here https://github.com/kiliankoe/dvbpy/pull/6

**Comment by kiliankoe** [comment]
Woohoo \o/ 

![](http://i.giphy.com/1zN2433DxGL4I.gif)
