### ISSUE TITLE
Add alternate methods for original response

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/dvbpy#3]
As a small addition to the current method that clean up the original response considerably, it'd be nice to have the option of getting the original responses as well.

**Comment by h4llow3En** [comment]
you could add a Bool to the functions params that have to be explicit called 

an example:
```python
def monitor(stop, offset=0, limit=10, city='Dresden', *, raw=False):
    # do stuff
    if raw:
        return raw_result
    # do stuff
```

**Comment by h4llow3En** [comment]
Added in aec0587b638d9e842f557a2084bce849e8b28854
