### ISSUE TITLE
Cleanup code

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/dvbpy#4]
There's a few things to be cleaned up. Coords returned as strings, unnecessary request parameters and stuff.

Also catch more exceptions on dictionary creation to prevent possible crashes on badly formatted data.

And what about possibly splitting this up across files? Does that make sense?

**Comment by h4llow3En** [comment]
started with cleanup in extra branch
ad09a9aab9175686093ec24cbc6a4b9ea92db086

**Comment by h4llow3En** [comment]
Much cleaner and documented

@kiliankoe, you have to edit the last params in the docstrings [here](https://github.com/kiliankoe/dvbpy/blob/master/dvb/dvb.py#L84) and [here](https://github.com/kiliankoe/dvbpy/blob/master/dvb/dvb.py#L251)

**Comment by kiliankoe** [comment]
✔️ 36540ae0bb0ff31a310a35befddefb058fe6ca8c
