### ISSUE TITLE
Publish on PyPI

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/dvbpy#5]

**Comment by kiliankoe** [comment]
Check out [tdolist's](https://github.com/tdolist/tdo/blob/master/setup.py#L15) setup.py, thanks @h4llow3En

**Comment by h4llow3En** [comment]
@kiliankoe, setup.py is ready you can upload

**Comment by kiliankoe** [comment]
![](http://i.giphy.com/3o6gaYpCy25SPkchSE.gif)

Thanks!
