### ISSUE TITLE
RS

### ISSUE THREAD

**Issue by hoodie** [kiliankoe/dvbpy#8]
wo bleibt dvb-rs?

**Comment by kiliankoe** [comment]
Was ein Issue 😄 

Aber ja, war ja eigentlich geplant 😕 Mal schauen, vielleicht irgendwann demnaechst mal. Wird als crate spätestens für einen matthias rewrite gebraucht :P

**Comment by kiliankoe** [comment]
Ich mach' das hier erstmal wieder zu, nimm's mir nicht übel :D
